/gate/geometry/setMaterialDatabase    data/GateMaterials.db

#
#     W O R L D
#
/gate/world/geometry/setXLength       .030 cm
/gate/world/geometry/setYLength       .030  cm
/gate/world/geometry/setZLength       .030  cm
#/gate/world/geometry/setXLength       400. mm
#/gate/world/geometry/setYLength       400. mm
#/gate/world/geometry/setZLength       400. mm

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#     D E F I N I T I O N   A N D   D E S C R I P T I O N         #
#           O F   G A M M A K N I F E   D E V I C E               #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# ----------------------------
# COBALT SOURCE AND COLLIMATOR
# ----------------------------

# CONTAINER
/gate/world/daughters/name                    container
/gate/world/daughters/insert                  cylinder
/gate/container/placement/setTranslation      0.0 0.0 0.0 mm
/gate/container/geometry/setRmax              100000 nm
/gate/container/geometry/setRmin              0.0 nm
/gate/container/geometry/setHeight            100000 nm
/gate/container/setMaterial                   Air
#/gate/container/vis/forceWireframe
/gate/container/vis/setColor                  yellow
/gate/container/placement/setRotationAxis     1 0 0
/gate/container/placement/setRotationAngle    90 deg

### CELL MEMBRANE
/gate/world/daughters/name                 cell_membrane
/gate/world/daughters/insert               box
/gate/cell_membrane/placement/setTranslation   0.0 0.0 0.0 nm
/gate/cell_membrane/geometry/setXLength        40012 nm
/gate/cell_membrane/geometry/setYLength        40012 nm
/gate/cell_membrane/geometry/setZLength        40012 nm
/gate/cell_membrane/setMaterial                Water
/gate/cell_membrane/vis/setColor               blue

### CELL MEMBRANE REPEATER
/gate/cell_membrane/repeaters/insert linear
/gate/cell_membrane/linear/setRepeatNumber 5
/gate/cell_membrane/linear/setRepeatVector 0. 0. 40012 nm

### CELL
/gate/cell_membrane/daughters/name                cell_body
/gate/cell_membrane/daughters/insert              box
/gate/cell_body/placement/setTranslation      0.0 0.0 0.0 nm
/gate/cell_body/geometry/setXLength           40000 nm
/gate/cell_body/geometry/setYLength           40000 nm
/gate/cell_body/geometry/setZLength           40000 nm
/gate/cell_body/setMaterial                   Water
/gate/cell_body/vis/setColor                  red

### NUCLEAR MEMBRANE
/gate/cell_body/daughters/name                     nuclear_membrane
/gate/cell_body/daughters/insert                   sphere
/gate/nuclear_membrane/placement/setTranslation    0.0 0.0 0.0 nm
/gate/nuclear_membrane/geometry/setRmax            2520 nm
/gate/nuclear_membrane/geometry/setRmin            0. nm
/gate/nuclear_membrane/setMaterial                 Water
/gate/nuclear_membrane/vis/setColor                green

### NUCLEUS
/gate/nuclear_membrane/daughters/name              nucleus
/gate/nuclear_membrane/daughters/insert            sphere
/gate/nucleus/placement/setTranslation             0.0 0.0 0.0 nm
/gate/nucleus/geometry/setRmax                     2500 nm
/gate/nucleus/geometry/setRmin                     0. nm
/gate/nucleus/setMaterial                          Water
/gate/nucleus/vis/setColor                         blue


### NUCLEOLUS
/gate/nucleus/daughters/name              nucleolus
/gate/nucleus/daughters/insert            sphere
/gate/nucleolus/placement/setTranslation             0.0 0.0 0.0 nm
/gate/nucleolus/geometry/setRmax                     500 nm
/gate/nucleolus/geometry/setRmin                     0. nm
/gate/nucleolus/setMaterial                          Water
/gate/nucleolus/vis/setColor                         red

### RIBOSOME
/gate/cell_body/daughters/name                ribosome
/gate/cell_body/daughters/insert              sphere
/gate/ribosome/placement/setTranslation       0 0 0 nm
/gate/ribosome/geometry/setRmax               25 nm
/gate/ribosome/geometry/setRmin               0. nm
/gate/ribosome/setMaterial                    Water
/gate/ribosome/vis/setColor                   red
/gate/ribosome/repeaters/insert cubicArray
/gate/ribosome/cubicArray/setRepeatNumberX 10
/gate/ribosome/cubicArray/setRepeatNumberY 10
/gate/ribosome/cubicArray/setRepeatNumberZ 10
/gate/ribosome/cubicArray/setRepeatVector 4000 4000 4000 nm
/gate/ribosome/cubicArray/autoCenter true

### GOLGI BODY
/gate/cell_body/daughters/name                golgi_container
/gate/cell_body/daughters/insert              sphere
/gate/golgi_container/placement/setTranslation 0 -5000 0 nm
/gate/golgi_container/geometry/setRmax        2500 nm
/gate/golgi_container/geometry/setRmin        2458 nm
/gate/golgi_container/setMaterial             Water
/gate/golgi_container/vis/setColor            green

