/gate/geometry/setMaterialDatabase    data/GateMaterials.db

#
#     W O R L D
#
/gate/world/geometry/setXLength       .030 cm
/gate/world/geometry/setYLength       .030  cm
/gate/world/geometry/setZLength       .030  cm
#/gate/world/geometry/setXLength       400. mm
#/gate/world/geometry/setYLength       400. mm
#/gate/world/geometry/setZLength       400. mm

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#     D E F I N I T I O N   A N D   D E S C R I P T I O N         #
#           O F   G A M M A K N I F E   D E V I C E               #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# ----------------------------
# COBALT SOURCE AND COLLIMATOR
# ----------------------------

# CONTAINER
/gate/world/daughters/name                      container
/gate/world/daughters/insert                    cylinder
/gate/container/placement/setTranslation        0.0 0.0 0.0 mm
/gate/container/geometry/setRmax                100000 nm
/gate/container/geometry/setRmin                0.0 nm
/gate/container/geometry/setHeight              100000 nm
/gate/container/setMaterial                     Air
#/gate/container/vis/forceWireframe
/gate/container/vis/setColor                    yellow
/gate/container/placement/setRotationAxis       1 0 0
/gate/container/placement/setRotationAngle      90 deg

### CELL MEMBRANE
/gate/world/daughters/name                      cell_membrane
/gate/world/daughters/insert                    box
/gate/cell_membrane/placement/setTranslation    0.0 0.0 0.0 nm
/gate/cell_membrane/geometry/setXLength         10012 nm
/gate/cell_membrane/geometry/setYLength         10012 nm
/gate/cell_membrane/geometry/setZLength         10012 nm
/gate/cell_membrane/setMaterial                 Cell_Membrane
/gate/cell_membrane/vis/setColor                blue

### CELL MEMBRANE REPEATER
/gate/cell_membrane/repeaters/insert            cubicArray
/gate/cell_membrane/cubicArray/setRepeatNumberX 1
/gate/cell_membrane/cubicArray/setRepeatNumberY 1
/gate/cell_membrane/cubicArray/setRepeatNumberZ 1
/gate/cell_membrane/cubicArray/setRepeatVector  10012 10012 10012 nm
/gate/cell_membrane/cubicArray/autoCenter       true

### CELL
/gate/cell_membrane/daughters/name              cell_body
/gate/cell_membrane/daughters/insert            box
/gate/cell_body/placement/setTranslation        0.0 0.0 0.0 nm
/gate/cell_body/geometry/setXLength             10000 nm
/gate/cell_body/geometry/setYLength             10000 nm
/gate/cell_body/geometry/setZLength             10000 nm
/gate/cell_body/setMaterial                     Cell_Body
/gate/cell_body/vis/setColor                    red

### NUCLEAR MEMBRANE
/gate/cell_body/daughters/name                  nuclear_membrane
/gate/cell_body/daughters/insert                sphere
/gate/nuclear_membrane/placement/setTranslation 0.0 0.0 0.0 nm
/gate/nuclear_membrane/geometry/setRmax         2520 nm
/gate/nuclear_membrane/geometry/setRmin         0. nm
/gate/nuclear_membrane/setMaterial              Nuclear_Membrane
/gate/nuclear_membrane/vis/setColor             green

### NUCLEUS
/gate/nuclear_membrane/daughters/name           nucleus
/gate/nuclear_membrane/daughters/insert         sphere
/gate/nucleus/placement/setTranslation          0.0 0.0 0.0 nm
/gate/nucleus/geometry/setRmax                  2500 nm
/gate/nucleus/geometry/setRmin                  0. nm
/gate/nucleus/setMaterial                       Nucleus
/gate/nucleus/vis/setColor                      blue


### NUCLEOLUS
/gate/nucleus/daughters/name                    nucleolus
/gate/nucleus/daughters/insert                  sphere
/gate/nucleolus/placement/setTranslation        0.0 0.0 0.0 nm
/gate/nucleolus/geometry/setRmax                500 nm
/gate/nucleolus/geometry/setRmin                0. nm
/gate/nucleolus/setMaterial                     Nucleolus
/gate/nucleolus/vis/setColor                    red

### ENDOPLASMIC RETICULUM
/gate/cell_body/daughters/name                  endo_retic
/gate/cell_body/daughters/insert                box
/gate/endo_retic/placement/setTranslation       3000 0 0 nm
/gate/endo_retic/geometry/setXLength            1000 nm
/gate/endo_retic/geometry/setYLength            1000 nm
/gate/endo_retic/geometry/setZLength            100 nm
/gate/endo_retic/setMaterial                    Water
/gate/endo_retic/vis/setColor                   cyan

### RIBOSOME
/gate/endo_retic/daughters/name                 ribosome
/gate/endo_retic/daughters/insert               sphere
/gate/ribosome/placement/setTranslation         0 0 0 nm
/gate/ribosome/geometry/setRmax                 25 nm
/gate/ribosome/geometry/setRmin                 0. nm
/gate/ribosome/setMaterial                      Ribosome
/gate/ribosome/vis/setColor                     red

### RIBOSOME REPEATER
/gate/ribosome/repeaters/insert                 cubicArray
/gate/ribosome/cubicArray/setRepeatNumberX      10
/gate/ribosome/cubicArray/setRepeatNumberY      10
/gate/ribosome/cubicArray/setRepeatNumberZ      1
/gate/ribosome/cubicArray/setRepeatVector       90 90 90 nm
/gate/ribosome/cubicArray/autoCenter            true

### ER REPEATER
/gate/endo_retic/repeaters/insert               ring
/gate/endo_retic/ring/setRepeatNumber           10
/gate/endo_retic/ring/setPoint1                 0 0 0 nm
/gate/endo_retic/ring/setPoint2                 0 1 1 nm
/gate/endo_retic/ring/enableAutoRotation        true

### GOLGI BODY
/gate/cell_body/daughters/name                  golgi_container
/gate/cell_body/daughters/insert                sphere
/gate/golgi_container/placement/setTranslation  0 0 0 nm
/gate/golgi_container/geometry/setRmax          2600 nm
/gate/golgi_container/geometry/setRmin          2558 nm
/gate/golgi_container/setMaterial               Golgi_Container
/gate/golgi_container/vis/setColor              green

### MITOCHONDRION
/gate/cell_body/daughters/name                  mitochondrion
/gate/cell_body/daughters/insert                ellipsoid
/gate/mitochondrion/placement/setTranslation    0 3500 0 nm
# x-length varies from 500 nm to 10000 nm
/gate/mitochondrion/geometry/setXLength         1000 nm
/gate/mitochondrion/geometry/setYLength         500 nm
/gate/mitochondrion/geometry/setZLength         500 nm
/gate/mitochondrion/setMaterial                 Mitochondria
/gate/mitochondrion/vis/setColor                yellow

### LYSOSOME
/gate/cell_body/daughters/name                  lysosome
/gate/cell_body/daughters/insert                sphere
/gate/lysosome/placement/setTranslation         0 0 3200 nm
/gate/lysosome/geometry/setRmin                 0 nm
# radius varies from 100 nm to 1200 nm
/gate/lysosome/geometry/setRmax                 500 nm
/gate/lysosome/setMaterial                      Lysosome
/gate/lysosome/vis/setColor                     yellow

### VACUOLE
/gate/cell_body/daughters/name                  vacuole
/gate/cell_body/daughters/insert                sphere
/gate/vacuole/placement/setTranslation          0 0 -3600 nm
/gate/vacuole/geometry/setRmin                  0 nm
# radius varies from 100 nm to 1200 nm
/gate/vacuole/geometry/setRmax                  900 nm
/gate/vacuole/setMaterial                       Vacuole
/gate/vacuole/vis/setColor                      magenta
